# Generated by Django 2.2.13 on 2020-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation_period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_water',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
